from typing import Optional

class LLMWrapper:
    def __init__(self):
        self.provider = None

    def set_provider(self, provider: str):
        self.provider = provider

    def generate(self, prompt: str) -> Optional[str]:
        # Dummy implementation
        return f"Generated by {self.provider}: {prompt}" 